config/routes.rb
Rails.application.routes.draw do
  resources :list_activities
  resources :activities
  root 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
    #belongs_to :list_activity
end

app/models/list_activity.rb
class ListActivity < ActiveRecord::Base
    has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:grade, :gradeoutof)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def GRADECALCULATOR
    render text: "Grade Calculator"   
  end 

end

app/controllers/list_activities_controller.rb
class ListActivitiesController < ApplicationController
  before_action :set_list_activity, only: [:show, :edit, :update, :destroy]

  # GET /list_activities
  # GET /list_activities.json
  def index
    @list_activities = ListActivity.all
  end

  # GET /list_activities/1
  # GET /list_activities/1.json
  def show
  end

  # GET /list_activities/new
  def new
    @list_activity = ListActivity.new
  end

  # GET /list_activities/1/edit
  def edit
  end

  # POST /list_activities
  # POST /list_activities.json
  def create
    @list_activity = ListActivity.new(list_activity_params)

    respond_to do |format|
      if @list_activity.save
        format.html { redirect_to @list_activity, notice: 'List activity was successfully created.' }
        format.json { render :show, status: :created, location: @list_activity }
      else
        format.html { render :new }
        format.json { render json: @list_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_activities/1
  # PATCH/PUT /list_activities/1.json
  def update
    respond_to do |format|
      if @list_activity.update(list_activity_params)
        format.html { redirect_to @list_activity, notice: 'List activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_activity }
      else
        format.html { render :edit }
        format.json { render json: @list_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_activities/1
  # DELETE /list_activities/1.json
  def destroy
    @list_activity.destroy
    respond_to do |format|
      format.html { redirect_to list_activities_url, notice: 'List activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_activity
      @list_activity = ListActivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_activity_params
      params.require(:list_activity).permit(:Name, :ShortName, :Grade, :Gradeoutof, :Percentage)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_activities_helper.rb
module ListActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :gradeoutof %><br>
    <%= f.text_field :gradeoutof %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Fix this grade</h1>

<%= render 'form' %>

<%= link_to 'Back to Grade Calculator', activities_path %>

app/views/activities/index.html.erb
<!DOCTYPE html>
<html>

<head>
<link rel="stylesheet" type="text/css" href="activities.css">
</head>

<p id="notice"><%= notice %></p>

<body>


<h1>Grade Calculator</h1>
<h3>Activities</h3>

<p>Give grades to the numeric activities:</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Name</th>
      <th>Grade</th>
      <th>Percentage</th>
      <th colspan="10"></th>
    </tr>
  </thead>


  <tbody>
    <% @activities.each do |activity| %>
    
      <tr>
        <td>Activity <%= activity.id %></td>
        <td>A<%= activity.id %></td>
        <td><%= activity.grade %> / <%= activity.gradeoutof %></td>
        <td><%= 100*activity.grade/activity.gradeoutof %>%</td>
        <td><%= link_to 'Fix this Grade', edit_activity_path(activity) %></td>
        <td><%= link_to 'Remove this Activity', activity, method: :delete, data: { confirm: 'Are you sure you want to delete this activity?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<thead>
      <tr>
      <th><b>TOTAL</b></th>
      <th colspan="3"></th>
    </tr>
</thead>
<br>

<button type="button" onclick="alert('Will fix to calculate average')">AVERAGE</button>
<button type="button" onclick="alert('Will fix to calculate mean')">MEAN</button>

<br>
<%= link_to 'Add an Activity', new_list_activity_path %>


</body>

</html>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade:</strong>
  <%= @activity.grade %>
</p>

<p>
  <strong>Gradeoutof:</strong>
  <%= @activity.gradeoutof %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/list_activities/_form.html.erb
<%= form_for(@list_activity) do |f| %>
  <% if @list_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_activity.errors.count, "error") %> prohibited this list_activity from being saved:</h2>

      <ul>
      <% @list_activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_area :Name %>
  </div>
  <div class="field">
    <%= f.label :ShortName %><br>
    <%= f.text_area :ShortName %>
  </div>
  <div class="field">
    <%= f.label :Grade %><br>
    <%= f.text_field :Grade %>
  </div>
  <div class="field">
    <%= f.label :Gradeoutof %><br>
    <%= f.text_field :Gradeoutof %>
  </div>
  <div class="field">
    <%= f.label :Percentage %><br>
    <%= f.text_field :Percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_activities/edit.html.erb
<h1>Editing List Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_activity %> |
<%= link_to 'Back', list_activities_path %>

app/views/list_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities - Give grades to the numeric activities:</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shortname</th>
      <th>Grade</th>
      <th>Gradeoutof</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_activities.each do |list_activity| %>
      <tr>
        <td><%= list_activity.Name %></td>
        <td><%= list_activity.ShortName %></td>
        <td><%= list_activity.Grade %></td>
        <td><%= list_activity.Gradeoutof %></td>
        <td><%= list_activity.Percentage %></td>
        <td><%= link_to 'Show', list_activity %></td>
        <td><%= link_to 'Edit', edit_list_activity_path(list_activity) %></td>
        <td><%= link_to 'Destroy', list_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<thead>
      <tr>
      <th><b>TOTAL</b></th>
      <th colspan="3"></th>
    </tr>
</thead>
<br>

<button type="button" onclick="alert('Will fix to calculate average')">AVERAGE</button>
<button type="button" onclick="alert('Will fix to calculate mean')">MEAN</button>

<br>
<%= link_to 'New List activity', new_list_activity_path %>

app/views/list_activities/new.html.erb
<h1>New List Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', list_activities_path %>

app/views/list_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list_activity.Name %>
</p>

<p>
  <strong>Shortname:</strong>
  <%= @list_activity.ShortName %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @list_activity.Grade %>
</p>

<p>
  <strong>Gradeoutof:</strong>
  <%= @list_activity.Gradeoutof %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @list_activity.Percentage %>
</p>

<%= link_to 'Edit', edit_list_activity_path(@list_activity) %> |
<%= link_to 'Back', list_activities_path %>